#!/usr/bin/env node
/**
 * Pull the web fonts out of Google Fonts and vendor them into fonts/.
 *
 * Self-hosting removes two extra DNS + TLS handshakes and a render-blocking
 * stylesheet from every page load. We keep only the latin and latin-ext
 * subsets — Chinese text falls through to the system CJK font either way,
 * which is exactly what happened with the hosted version too.
 *
 * Run: node scripts/fetch-fonts.mjs
 */
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outDir = resolve(root, "fonts");

// A Chrome UA is what makes Google serve woff2 with unicode-range subsets.
const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 " +
  "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

// Only the faces the stylesheet actually asks for:
//   serif  — body copy and headings, plus italic for .motto and <em> in prose
//   sans   — nav, buttons, captions (no italic anywhere)
//   mono   — code blocks and eyebrows (single weight)
//
// These are pinned to single weights on purpose. Asking Google for a weight
// *range* returns the variable font, and Source Serif 4's variable file is
// 119 KB against 20 KB for one static cut — six times the bytes to render the
// same two weights this design uses.
const FACES = [
  {
    file: "source-serif-4-400",
    query: "Source+Serif+4:wght@400",
    family: "Source Serif 4",
    style: "normal",
    weight: "400",
  },
  {
    file: "source-serif-4-600",
    query: "Source+Serif+4:wght@600",
    family: "Source Serif 4",
    style: "normal",
    weight: "600",
  },
  {
    file: "source-serif-4-400-italic",
    query: "Source+Serif+4:ital,wght@1,400",
    family: "Source Serif 4",
    style: "italic",
    weight: "400",
  },
  {
    file: "source-sans-3-400",
    query: "Source+Sans+3:wght@400",
    family: "Source Sans 3",
    style: "normal",
    weight: "400",
  },
  {
    file: "source-sans-3-600",
    query: "Source+Sans+3:wght@600",
    family: "Source Sans 3",
    style: "normal",
    weight: "600",
  },
  {
    file: "ibm-plex-mono-400",
    query: "IBM+Plex+Mono:wght@400",
    family: "IBM Plex Mono",
    style: "normal",
    weight: "400",
  },
];

const KEEP = new Set(["latin", "latin-ext"]);

async function fetchText(url) {
  const res = await fetch(url, { headers: { "User-Agent": UA } });
  if (!res.ok) throw new Error(`${res.status} ${url}`);
  return res.text();
}

/** Split a Google Fonts stylesheet into { subset, unicodeRange, url } blocks. */
function parseBlocks(css) {
  const blocks = [];
  const re = /\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*\{([^}]+)\}/g;
  let m;
  while ((m = re.exec(css))) {
    const [, subset, body] = m;
    const url = body.match(/url\((https:\/\/[^)]+\.woff2)\)/)?.[1];
    const range = body.match(/unicode-range:\s*([^;]+);/)?.[1]?.trim();
    if (url && range) blocks.push({ subset, url, range });
  }
  return blocks;
}

await mkdir(outDir, { recursive: true });

const rules = [];
let total = 0;

for (const face of FACES) {
  const css = await fetchText(
    `https://fonts.googleapis.com/css2?family=${face.query}&display=swap`
  );
  const blocks = parseBlocks(css).filter((b) => KEEP.has(b.subset));
  if (!blocks.length) throw new Error(`no latin subset found for ${face.family}`);

  for (const block of blocks) {
    const name = `${face.file}-${block.subset}.woff2`;
    const res = await fetch(block.url, { headers: { "User-Agent": UA } });
    if (!res.ok) throw new Error(`${res.status} ${block.url}`);
    const bytes = Buffer.from(await res.arrayBuffer());
    await writeFile(resolve(outDir, name), bytes);
    total += bytes.length;
    console.log(`  ${name.padEnd(38)} ${(bytes.length / 1024).toFixed(1)} KB`);

    rules.push(
      [
        "@font-face {",
        `  font-family: "${face.family}";`,
        `  font-style: ${face.style};`,
        `  font-weight: ${face.weight};`,
        "  font-display: swap;",
        `  src: url("../fonts/${name}") format("woff2");`,
        `  unicode-range: ${block.range};`,
        "}",
      ].join("\n")
    );
  }
}

const header = [
  "// Generated by scripts/fetch-fonts.mjs — do not edit by hand.",
  "// Self-hosted so the browser never has to reach fonts.googleapis.com.",
  "",
].join("\n");

await writeFile(resolve(root, "_sass/_fonts.scss"), header + rules.join("\n\n") + "\n");
console.log(`\n${rules.length} faces, ${(total / 1024).toFixed(1)} KB total → _sass/_fonts.scss`);
